name: Notification on push

on:
  push:
    branches:
    - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Discord push notification
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        DISCORD_USERNAME: GitHub
        DISCORD_AVATAR: https://cdn.unix.lu/kraken.webp
        DISCORD_MULTILINE: 1
      uses: ezworx/action-discord@main
      with:
        args: '🚀✨ - Commit has been pushed to {{ EVENT_PAYLOAD.repository.full_name }}.\n✨ - Commi: {{ EVENT_PAYLOAD.commits[0].message }}.'
    - name: Discord notification
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      uses: ezworx/action-discord@main        